version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: cop-nginx
    volumes:
      - .:/srv/copmusic:ro
      - ./docker/build/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/volumes/nginx/log/:/var/log/nginx/
    ports:
      - 8080:80
    depends_on:
      - php-fpm
    networks:
      copmusic:
        aliases:
          - copmusic.local
  php-fpm:
    build:
      context: docker/build/php-fpm
      args:
        USER_ID: ${CURRENT_USER_ID}
    image: copmusic/php-fpm
    container_name: cop-php-fpm
    volumes:
      - .:/srv/copmusic
      - ./docker/build/php-fpm/supervisor.conf:/etc/supervisor/conf.d/supervisor.conf
      - ./docker/volumes/data:/var/log/supervisor
      - ./docker/volumes/data:/opt/data
    networks:
      - copmusic
    environment:
      PHP_IDE_CONFIG: serverName=copmusic.local

  postgres:
    image: postgres:11.5-alpine
    container_name: cop-postgres
    hostname: cop-postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: copmusic
    volumes:
      - ./docker/volumes/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - copmusic

  redis:
    image: redis:latest
    container_name: cop-redis
    ports:
      - 6379:6379
    volumes:
      - ./docker/volumes/redis:/var/lib/redis
    environment:
      REDIS_PORT: 6379
    restart: always
    networks:
      - copmusic

  websockets:
    build: docker/build/websockets
    image: copmusic/websockets
    container_name: cop-websockets
    volumes:
      - .:/srv/copmusic
    restart: always
    ports:
      - 6001:6001
    depends_on:
      - redis
    networks:
      - copmusic

  go-media-fetcher:
    image: mihaershv/go-media-fetcher
    container_name: cop-go-media-fetcher
    env_file:
      - .env.docker
    environment:
      - YOUTUBE_DATA_API_V3_KEY=${YOUTUBE_DATA_API_V3_KEY}
    ports:
      - 8090:8090
    networks:
      - copmusic

networks:
  copmusic:
    external: true
